# Copyright (c) 2010-2021, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

name: Upload Coverage
description: Upload coverage to codecov

inputs:
  name:
    description: "Job name"
    required: true
  project_dir:
    description: "Path to the project directory"
    required: true

runs:
  using: "composite"

  steps:
    - run: |
        cd ${{ inputs.project_dir }}
        cov_dirs="${{ inputs.coverage-directories }}"
        dirs_opts=""
        if [[ -n "${cov_dirs}" ]];
        then
            for dir in ${cov_dirs}; do dirs_opts+=" --directory=${dir}"; done
        lcov --no-external --gcov-tool gcov ${dirs_opts} --capture --output-file ${{ inputs.report }}
        curl -o codecov.sh -f https://codecov.io/bash || \
          curl -o codecov.sh -f https://codecov.io/bash || \
          curl -o codecov.sh -f https://codecov.io/bash
        bash codecov.sh -n "${{ inputs.name }}"
      shell: bash
