# Copyright (c) 2010-2021, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

name: Upload Coverage
description: Upload coverage to codecov, requires lcov.

inputs:
  name:
    description: "Job name"
    required: true
  project_dir:
    description: "Path to the project directory"
    required: true
  directories:
    descripton: "List of directories to look for coverage info"
    required: false
  config_file:
    description: "Config file to use, otherwise let codecov use codecov.yml"
    required: false


runs:
  using: "composite"

  steps:
    - run: |
        cd ${{ inputs.project_dir }};
        # Allow user to change codecov config file (and use a hidden one).
        config_file="${{ inputs.config_file }}";
        if [[ -n "${config_file}" ]]; then
          cp -f ${config_file} codecov.yml
        fi
        # Restrict search to directories listed, if any.
        directory_list="${{ inputs.directories }}";
        dirs_opts="";
        if [[ -n "${directory_list}" ]]; then
          for dir in ${directory_list}; do dirs_opts+=" --directory=${dir}"; done
        fi
        # Generate the coverage report.
        lcov --no-external --gcov-tool gcov ${dirs_opts} --capture --output-file lcov.info;
        # Download the coverage export script.
        curl --silent --output codecov --fail https://codecov.io/bash || \
          curl -s -o codecov -f https://codecov.io/bash;
        VERSION=$(grep -o 'VERSION=\"[0-9\.]*\"' codecov | cut -d'"' -f2);
        for i in 1 256 512
        do
          shasum -a $i -c --ignore-missing <(curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM") || \
          shasum -a $i -c <(curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM")
        done
        # Effectively export the coverage report.
        bash codecov.sh -n "${{ inputs.name }}" -X gcov;
      shell: bash
